### ISSUE TITLE
Features still *appear* to be locked on Friday

### ISSUE THREAD

**Issue by dailycavalier** [mozilla/firehug#100]
After signing into the app on Friday, this message appears below the menu items:
"Healthy Dialog" and "3 Questions" are only available Friday to Sunday.

The message disappears and the mentioned sections appear in the menu once the page is reloaded. Ideally, a refresh is not needed and the full menu appears after sign-in.

**Comment by CyborgShadow** [comment]
Does not appear in the menu post refresh on ff24 on mac.

**Comment by digitarald** [comment]
Fixed on prod, please re-test. Removed lock completely!
