### ISSUE TITLE
Expire the cache to enable all features

### ISSUE THREAD

**Issue by dailycavalier** [mozilla/firehug#102]
I think we're hitting caching issues that are causing weirdness with the menus and what actions people can perform. I suggest we expire our cache to make sure users are getting the latest code for the app.

For example, one person using iPhone Safari tried to fill out the 3 Questions form for the first time and was shown this message before even seeing the form: "You can answer the 3 Questions again after two hours have elapsed. Now go have fun at the Summit!". Once this person cleared their cache and cookies, everything behaved as expected.

**Comment by digitarald** [comment]
Frontend cache is set to one hour, this should be fixed by now
