### ISSUE TITLE
Current Summit day for frontend

### ISSUE THREAD

**Issue by digitarald** [mozilla/firehug#38]
Schedule, Dialog and Survey need to know about the current day of the month.

The frontend is initialized with a payload https://github.com/digitarald/firehug/blob/master/app.js#L69 . This data should contain a `day` value depending on the timezone of the users `location`.

The code should be shared, so the Survey can validate that it is activated. We can hardcode the the timezone for Brussels, Toronto and Santa Clara.

**Comment by operatorjen** [comment]
https://github.com/digitarald/firehug/commit/f2d57362f4982450e719e0d96dc95051cb7b6d02
