### ISSUE TITLE
Add text to Welcome / sign-in page

### ISSUE THREAD

**Issue by dailycavalier** [mozilla/firehug#40]
In place of the David text on the welcome page, let's show this welcome message. It would be nice to have the text appear on four lines as shown below and might be best centered (I'll leave that up to you):

The Summit is a human conference.
A meet-up of grand proportion.
A full 72 hours/4,320 minutes/259,200 seconds of magic,
wholly dedicated to our awesome community, you.

**Comment by operatorjen** [comment]
https://github.com/digitarald/firehug/commit/a8cd2bba7f042ed8a68129990818b812c56288d4
