### ISSUE TITLE
Use 12 hour time format in schedule

### ISSUE THREAD

**Issue by dailycavalier** [mozilla/firehug#46]
Let's switch from 24-hour to 12-hour time format in the schedule and also remove the seconds from showing. For example: "14:15:00 - 14:45:00" becomes "2:15pm - 2:45pm"

**Comment by operatorjen** [comment]
This is taken from the spreadsheet verbatim, so just update the times on that end

**Comment by digitarald** [comment]
Please fix in spreadsheet (probably remove time validation from column)

**Comment by dailycavalier** [comment]
Fixed in the spreadsheet!
