### ISSUE TITLE
Getting Around screen

### ISSUE THREAD

**Issue by digitarald** [mozilla/firehug#49]

**Comment by dailycavalier** [comment]
Here's an outline of the Getting Around content. Feel free to use placeholder text in each section, and we'll have the final content available by end of tomorrow. Keep in mind that the content in this section will be different for each location, so it would be nice to have a location dropdown menu similar to the Schedule view.

In Markdown format (just replace ~ with #)

~ How to have a great Summit in five easy steps
~~ Participate
~~ Make room
~~ Practice respect
~~ Be helpful
~~ Have fun

~ At the Summit
~~ Meet the speakers
~~ Get Social

~ Travel logistics
~~ To/from Hotel
~~ Hotel
~~ Venue
~~ Lounge hours

~ Travel Tips
~~ Where to exchange money
~~ Weather
~~ Fact about the city
~~ How close is the nearest Mozilla space?
~~ Language(s) spoken
~~ Currency
~~ Parking
~~ Tipping
~~ Where to go for help

~ In case you missed it
~~ Help
~~ Smoking
~~ Photos

**Comment by operatorjen** [comment]
https://github.com/digitarald/firehug/commit/09d08e343c996a40a11986e27083cb5c76314f38
