### ISSUE TITLE
Update list of moods in 3 Questions form

### ISSUE THREAD

**Issue by dailycavalier** [mozilla/firehug#51]
The Summit organizers have asked that we use this list of moods instead of the five we currently have. Could you try adding these and we can see how it looks?

Excited, Worried, Proud, Confused, Inspired, Curious, Lost, Ready, Bored

**Comment by operatorjen** [comment]
Would it make sense to limit this to just 5? 9 seems like a lot to go through in such a small screen space.

**Comment by dailycavalier** [comment]
Agreed. Let's try these five: Excited, Worried, Proud, Confused, Curious.

**Comment by operatorjen** [comment]
I almost posted the wrong link in here.. let's try something more pg-rated https://github.com/digitarald/firehug/commit/828c742937763cdf91a02f5863d541219b2ecdba
