### ISSUE TITLE
Center the location dropdown in mobile view

### ISSUE THREAD

**Issue by dailycavalier** [mozilla/firehug#52]
In the tablet/desktop view, the placement of location dropdown looks great. In the mobile view, it looks odd since the elements above and below it are centered in the screen. I suggest we position the location dropdown in the center of the screen in the mobile view, and we make the width of the dropdown equal to the width of the "SCHEDULE" header.

**Comment by operatorjen** [comment]
https://github.com/digitarald/firehug/commit/0be76612f6b0b149abe3ec939bf755fa766c020a

**Comment by dailycavalier** [comment]
Sorry if this is a nitpick, but the location dropdown only appears centered on a screen width of 430px. It would be nice if it were centered on common screen widths like 320px and 480px, similar to how the schedule and month day content are always centered :)

**Comment by operatorjen** [comment]
https://github.com/digitarald/firehug/commit/d08469c856b7df7a761765a438f64f554d7c8a61
