### ISSUE TITLE
Update Mozillian selector placeholder text

### ISSUE THREAD

**Issue by dailycavalier** [mozilla/firehug#54]
Let's make it clear to Mozillians that they can only search and add people who are at their same Summit location.

Old text: "Add a Mozillian ..."
New text: "Add a Mozillian at CITY..." where CITY is the user's Summit location

**Comment by operatorjen** [comment]
https://github.com/digitarald/firehug/commit/59c5b376e9f8c92cb8c7acfe24ceef5b61d18fde
