### ISSUE TITLE
Add privacy and legal policies

### ISSUE THREAD

**Issue by dailycavalier** [mozilla/firehug#60]

**Comment by operatorjen** [comment]
@dailycavalier  Where do you want this? Links in the footer?

**Comment by dailycavalier** [comment]
A link in the footer of the app would be great. We can also link to the
privacy policy from the Persona login window. That would be nice to do.
Thanks!

On Tue, Oct 1, 2013 at 2:15 PM, Jen Fong-Adwent notifications@github.comwrote:

> Where do you want this? Links in the footer?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/digitarald/firehug/issues/60#issuecomment-25490313
> .

## 

William

**Comment by digitarald** [comment]
Links are in the menu now.
