### ISSUE TITLE
Schedule data is not in the same order as Spreadsheet data

### ISSUE THREAD

**Issue by digitarald** [mozilla/firehug#63]
Schedule for Toronto - Friday

AM events come after PM events. `Hack Space` should be second.

**Comment by pfinette** [comment]
Same for the other locations.

![schedule order](https://f.cloud.github.com/assets/307225/1239139/31b249a0-29f6-11e3-8d75-7c174073a677.png)

**Comment by pfinette** [comment]
And on this note: AM/PM is a North American thing. At least for Brussels we should use the 24h time format (which is the standard in Europe and I believe in Canada as well). AM/PM is actually pretty hard to grock for people who are not familiar to it.

**Comment by digitarald** [comment]
Localized times are not in the app scope. @dailycavalier can change the format any time in the Schedule spreadsheet.

**Comment by dailycavalier** [comment]
@pfinette I updated the times in the Brussels schedule to use the 24h time format. Do you recommend using that format for Toronto or Santa Clara too?

**Comment by digitarald** [comment]
All-numeric format are usually considered more unambiguous and are a more widely accepted standard [1](http://en.wikipedia.org/wiki/Date_and_time_representation_by_country#Time)

**Comment by operatorjen** [comment]
https://github.com/digitarald/firehug/commit/575809004ed19fd747da0b0b1531d210fb18c66b
