### ISSUE TITLE
Schedule thinks I go to Toronto (I am going to Santa Clara)

### ISSUE THREAD

**Issue by pfinette** [mozilla/firehug#67]
On the mobile view I get dropped into the Toronto view, on the desktop experience I see only the dropdown without a preselected location.

![empty schedule on desktop](https://f.cloud.github.com/assets/307225/1239129/ffdaca38-29f5-11e3-90d5-f31a895062a7.png)

**Comment by digitarald** [comment]
Duplicate of #64
