### ISSUE TITLE
The Back button is small (on mobile) and impossible to find (on desktop)

### ISSUE THREAD

**Issue by pfinette** [mozilla/firehug#68]
Make that sucker more prominent! :)

![back button](https://f.cloud.github.com/assets/307225/1239163/afd3253e-29f6-11e3-922f-f7a1897fa9ec.png)

**Comment by digitarald** [comment]
Ideas
- Make this a home button
- Make the navigation align with the content, using the same columns/offset (review all column/offset values using in various screens)

**Comment by dailycavalier** [comment]
I like the idea to have the navigation align with the content, using the
same columns/offset (review all column/offset values using in various
screens). I suggest having both the back and hamburger icons align with the
content.

On Mon, Sep 30, 2013 at 11:09 AM, Harald Kirschner <notifications@github.com

> wrote:
> 
> Ideas
> - Make this a home button
> - Make the navigation align with the content, using the same
>   columns/offset (review all column/offset values using in various screens)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/digitarald/firehug/issues/68#issuecomment-25387701
> .

## 

William

**Comment by digitarald** [comment]
Fixed in 32402c025efdab6afe8ee4536435dba3d4fceb21 , will ask lee what he thinks about tweaking the button to a home button
