### ISSUE TITLE
Line break on initial screen is funky

### ISSUE THREAD

**Issue by pfinette** [mozilla/firehug#71]
See screenshot:

![funky linebreak](https://f.cloud.github.com/assets/307225/1239263/e2528d50-29f7-11e3-82b6-b3dc85c9de1a.png)

**Comment by digitarald** [comment]
Before Lee does a final design review we need to balance the typo here, this is the first impression of the app.

**Comment by digitarald** [comment]
Remove extra paragraph space, except the first line.
