### ISSUE TITLE
Add "Day planner view" link at top of Schedule

### ISSUE THREAD

**Issue by dailycavalier** [mozilla/firehug#72]
The Schedule list does a fantastic job at providing details for each session, but we could make it easier for people to get an overview of the day's activities, specifically so they can plan which sessions to go to.

Pascal and I suggest having a link at the top of the Schedule view that says something like "Day planner view" and links to an image. There will be a unique image for each of the three main days and each of the three cities (9 images total), so the destination of the link would depend on the location and day you are looking at in the schedule. Pascal has offered to get these images created as soon as possible.

@digitarald - if you like this idea and it seems fairly easy to add these links, do you have ideal image dimensions in mind? Perhaps 640x960, which is twice as wide and tall as a Firefox OS device screen.

**Comment by digitarald** [comment]
I understand the need to have a more organized quick overview of the daily events. Would it help if we clean up the schedule view to use the space more efficient and allow people to switch between compact grid and extended list view? I can provide mock ups or a quick prototype to make this clearer.

**Comment by dailycavalier** [comment]
Yes, that would help :) Would be great to see some mock ups to better understand. Thanks!
