### ISSUE TITLE
Can't close logout dropdown by clicking "three lines" menu icon on Firefox for Android

### ISSUE THREAD

**Issue by alefteris** [mozilla/firehug#73]
Trying firehug from the dev site on Firefox for Android. I click the 3 lines menu button and dropdown (logout option) expands, but I can't click the menu button again to close the dropdown. I have to click at an empty space so that the dropdown closes.

**Comment by digitarald** [comment]
I agree that it is unintuitive on touch screens. P2 as we don't have much content in that menu.
