### ISSUE TITLE
Add static content for 'Tips and random bits' (formerly Getting around)

### ISSUE THREAD

**Issue by dailycavalier** [mozilla/firehug#78]
Please change the title to this section in the menu to 'Tips and random bits' and update the content to use what is in this document: https://docs.google.com/document/d/1Nnwh0nSN8EyBEUd0Q8OakhlEouVWS4pyX3Y00mUbnoA/edit?usp=sharing

**Comment by dailycavalier** [comment]
Please use the latest version of this document, which has had some changes in the last few hours. Thanks!

**Comment by operatorjen** [comment]
https://github.com/digitarald/firehug/commit/1110f453cf3155f80d5cbe20cb28b1f69565e3a2
