### ISSUE TITLE
Check if the app is already installed

### ISSUE THREAD

**Issue by dailycavalier** [mozilla/firehug#94]
We can do a simple check to see if the app is already installed. Dietrich ran into this issue when testing. He installed the app, uninstalled it, and then received an error message saying he couldn't install it again. He says that if we add this check, that bug will be fixed.

Documentation
https://developer.mozilla.org/en-US/docs/Web/API/Apps.checkInstalled

**Comment by digitarald** [comment]
We are doing that. If it is not working, it is a platform bug. Closing, but still curious which device.
