### ISSUE TITLE
Firefox Nightly doesn't display all the events that Release/Mobile does

### ISSUE THREAD

**Issue by Standard8** [mozilla/firehug#97]
Viewing https://summit.mozilla.org/#!/schedule on Firefox Nightly for Brussels on Friday, gives me an "Open Room" as the last thing before the 16:00 Break.

On Release, I see Firefox for Android as a session.

**Comment by digitarald** [comment]
We removed caching, does that fix it?

**Comment by Standard8** [comment]
Yep, this is fine now. Thanks!
