### ISSUE TITLE
Session times don't appear on Keon

### ISSUE THREAD

**Issue by dailycavalier** [mozilla/firehug#99]
Someone showed me the schedule view on a Keon and the agenda times did not appear in portrait mode. When the phone was flipped to landscape mode the times appear. When switched back to portrait mode, the times disappear.

**Comment by digitarald** [comment]
Am I right to assume that this happens with long event location names?

**Comment by digitarald** [comment]
It seems to be a render engine bug. The times appear occasionally after rotating the device to landscape and back. The space is also correct where the test should be. Will be hard to fix
